services:
  - type: web
    name: recicle-ja
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn recicle_ja.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.13.1"
