# Generated by Django 6.0.6 on 2026-06-06 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Material')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('instrucoes_preparo', models.TextField(verbose_name='Instruções de Preparo')),
                ('icone', models.CharField(blank=True, help_text='Ex: bi-recycle, bi-box, bi-droplet', max_length=50, verbose_name='Ícone (Bootstrap Icons)')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiais',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='PontoDeColeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do Ecoponto')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço Completo')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitude')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('materiais_aceitos', models.ManyToManyField(related_name='pontos_coleta', to='reciclagem.material', verbose_name='Materiais Aceitos')),
            ],
            options={
                'verbose_name': 'Ponto de Coleta',
                'verbose_name_plural': 'Pontos de Coleta',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, verbose_name='Nome (opcional)')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail (opcional)')),
                ('tipo_feedback', models.CharField(choices=[('sugestao', 'Sugestão de Novo Ponto'), ('manutencao', 'Relato de Problema/Manutenção'), ('outro', 'Outros Assuntos')], default='sugestao', max_length=20, verbose_name='Tipo de Feedback')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('lido', models.BooleanField(default=False, verbose_name='Lido/Revisado')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('ponto_coleta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='reciclagem.pontodecoleta', verbose_name='Ponto de Coleta Referente')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
                'ordering': ['-criado_em'],
            },
        ),
    ]
