# Generated by Django 6.0.6 on 2026-06-10 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciclagem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalDeDescarte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locais_descarte', to='reciclagem.material')),
                ('ponto_coleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locais_descarte', to='reciclagem.pontodecoleta')),
            ],
        ),
    ]
