# Generated by Django 6.0.6 on 2026-06-10 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciclagem', '0002_localdedescarte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pontodecoleta',
            name='ativo',
        ),
        migrations.AddField(
            model_name='pontodecoleta',
            name='horario_funcionamento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Horário de Funcionamento'),
        ),
        migrations.AddField(
            model_name='pontodecoleta',
            name='status',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Indisponível', 'Indisponível'), ('Em manutenção', 'Em manutenção')], default='Ativo', max_length=20, verbose_name='Status'),
        ),
    ]
